version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j_paradise_papers
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_paradise_papers-data:/data
      - neo4j_paradise_papers-plugins:/plugins
volumes:
  neo4j_paradise_papers-data:
  neo4j_paradise_papers-plugins: